#!/bin/bash

createSymlink() {
    if [ "$2" ]; then
        rm "$2"
    fi
    ln -s "$1" "$2"
    echo "Created symlink to $1"
}

createCodeSymlink() {
    createSymlink `pwd`/$1 ~/Library/Application\ Support/Code/User/$1
}

installExtension() {
    code --install-extension $1
}

uninstallExtension() {
    code --uninstall-extension $1
}

createCodeSymlink settings.json
createCodeSymlink keybindings.json

installExtension dkundel.vscode-npm-source
installExtension donjayamanne.githistory
installExtension eg2.tslint
installExtension eg2.vscode-npm-script
installExtension fknop.vscode-npm
installExtension christian-kohler.path-intellisense
installExtension waderyan.gitblame
installExtension emilast.LogFileHighlighter

uninstallExtension robertohuertasm.vscode-icons